services:
  - type: web
    name: site-st-api
    runtime: node
    rootDir: aliancapanorama-src
    buildCommand: pnpm install --no-frozen-lockfile && pnpm --filter @workspace/api-server run build
    startCommand: node --enable-source-maps artifacts/api-server/dist/index.mjs
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
